/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poo.capitulo5.proyecto;

import java.awt.Image;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author pc ponce
 */
public class FrmBici extends javax.swing.JFrame {

    //decalracion de bicicletas
    Bicicleta bici3 = new Bicicleta("Aluminio", "SpeedFox", "Gris", "BMC Bikes", 10499.00);
    Bicicleta bici2 = new Bicicleta("Fibra de carbono", "S-Works Turbo Levo", "Rojo", "Specialized", 11600.00);
    Bicicleta bici1 = new Bicicleta("Acero Inosidable", "Rallon M LTD", "Verde", "Orbea", 1200.00);
    //ArrayList <Bicicleta> bicis = new ArrayList<>()    
    ImageIcon Rallon = new ImageIcon(getClass().getResource("/Bicicletas/Rallon M LTD Verde.jpg"));
    ImageIcon Turbo = new ImageIcon(getClass().getResource("/Bicicletas/S-Works Turbo Levo Rojo.jpg"));
    ImageIcon SpeedFox = new ImageIcon(getClass().getResource("/Bicicletas/SpeedFox Gris.jpg"));
    

    /**
     * Creates new form GUImoto
     */
    public FrmBici() {
        initComponents();
        //ocultar panel
        pnlBici.setVisible(false);
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnReservarBici = new javax.swing.JButton();
        btnMostrarInfoBici = new javax.swing.JButton();
        cmbBicicletas = new javax.swing.JComboBox<>();
        lblBicicleta = new javax.swing.JLabel();
        pnlBici = new javax.swing.JPanel();
        btnCerrar = new javax.swing.JButton();
        lblImage = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaInfo = new javax.swing.JTextArea();
        lblFondoBicicleta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bicicletas");
        setMaximumSize(new java.awt.Dimension(505, 602));
        setMinimumSize(new java.awt.Dimension(505, 602));
        getContentPane().setLayout(null);

        btnReservarBici.setBackground(new java.awt.Color(0, 0, 0));
        btnReservarBici.setFont(new java.awt.Font("Wide Latin", 0, 12)); // NOI18N
        btnReservarBici.setForeground(new java.awt.Color(255, 255, 255));
        btnReservarBici.setText("Reservar");
        getContentPane().add(btnReservarBici);
        btnReservarBici.setBounds(190, 230, 130, 40);

        btnMostrarInfoBici.setBackground(new java.awt.Color(0, 0, 0));
        btnMostrarInfoBici.setFont(new java.awt.Font("Wide Latin", 0, 12)); // NOI18N
        btnMostrarInfoBici.setForeground(new java.awt.Color(255, 255, 255));
        btnMostrarInfoBici.setText("Ver info de la bici");
        btnMostrarInfoBici.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarInfoBiciActionPerformed(evt);
            }
        });
        getContentPane().add(btnMostrarInfoBici);
        btnMostrarInfoBici.setBounds(140, 180, 230, 30);

        cmbBicicletas.setBackground(new java.awt.Color(0, 0, 0));
        cmbBicicletas.setFont(new java.awt.Font("Wide Latin", 0, 12)); // NOI18N
        cmbBicicletas.setForeground(new java.awt.Color(255, 255, 255));
        cmbBicicletas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una bicicleta...", "Rallon M LTD -Verde-", "S-Works Turbo Levo -Rojo-", "SpeedFox -Gris-" }));
        getContentPane().add(cmbBicicletas);
        cmbBicicletas.setBounds(90, 120, 330, 40);

        lblBicicleta.setBackground(new java.awt.Color(0, 0, 0));
        lblBicicleta.setFont(new java.awt.Font("Wide Latin", 0, 36)); // NOI18N
        lblBicicleta.setForeground(new java.awt.Color(255, 255, 255));
        lblBicicleta.setText("Bicicletas");
        getContentPane().add(lblBicicleta);
        lblBicicleta.setBounds(100, 30, 310, 70);

        pnlBici.setBackground(new java.awt.Color(102, 102, 102));
        pnlBici.setLayout(null);

        btnCerrar.setBackground(new java.awt.Color(102, 102, 102));
        btnCerrar.setFont(new java.awt.Font("Wide Latin", 0, 12)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        pnlBici.add(btnCerrar);
        btnCerrar.setBounds(170, 237, 110, 40);
        pnlBici.add(lblImage);
        lblImage.setBounds(20, 20, 270, 210);

        jScrollPane1.setBackground(new java.awt.Color(204, 204, 204));

        txaInfo.setColumns(20);
        txaInfo.setFont(new java.awt.Font("Wide Latin", 0, 12)); // NOI18N
        txaInfo.setRows(5);
        jScrollPane1.setViewportView(txaInfo);

        pnlBici.add(jScrollPane1);
        jScrollPane1.setBounds(300, 30, 166, 200);

        getContentPane().add(pnlBici);
        pnlBici.setBounds(20, 290, 470, 290);

        lblFondoBicicleta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondos/Fondo Interfaz Bicicleta.png"))); // NOI18N
        getContentPane().add(lblFondoBicicleta);
        lblFondoBicicleta.setBounds(0, 0, 508, 640);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMostrarInfoBiciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarInfoBiciActionPerformed
        
        int index = cmbBicicletas.getSelectedIndex();
        
        //switch para mostar solo el vehiculo solicitado
        switch(index){
            case 1 :
                pnlBici.setVisible(true);
                Icon imgRallon = new ImageIcon(Rallon.getImage().getScaledInstance(lblImage.getWidth(), lblImage.getHeight(), Image.SCALE_DEFAULT));
                lblImage.setIcon(imgRallon);
                txaInfo.setText(bici1.presentarInfo());
            
                break;
            case 2:
                pnlBici.setVisible(true);
                Icon imgTurbo = new ImageIcon(Turbo.getImage().getScaledInstance(lblImage.getWidth(), lblImage.getHeight(), Image.SCALE_DEFAULT));
                lblImage.setIcon(imgTurbo);
                txaInfo.setText(bici2.presentarInfo());
                
                break;
            case 3:
                pnlBici.setVisible(true);
                Icon imgSpeedFox = new ImageIcon(SpeedFox.getImage().getScaledInstance(lblImage.getWidth(), lblImage.getHeight(), Image.SCALE_DEFAULT));
                lblImage.setIcon(imgSpeedFox);
                txaInfo.setText(bici3.presentarInfo());
                
                break;
            default :
                JOptionPane.showMessageDialog(rootPane, "Seleccione una bicicleta para continuar ");
                break;
        }
        
    }//GEN-LAST:event_btnMostrarInfoBiciActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        pnlBici.setVisible(false);
        cmbBicicletas.setSelectedIndex(0);
    }//GEN-LAST:event_btnCerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmBici.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmBici.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmBici.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmBici.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmBici().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnMostrarInfoBici;
    private javax.swing.JButton btnReservarBici;
    private javax.swing.JComboBox<String> cmbBicicletas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBicicleta;
    private javax.swing.JLabel lblFondoBicicleta;
    private javax.swing.JLabel lblImage;
    private javax.swing.JPanel pnlBici;
    private javax.swing.JTextArea txaInfo;
    // End of variables declaration//GEN-END:variables
}
