/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poo.capitulo5.proyecto;

import java.awt.Image;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author pc ponce
 */
public class FrmMoto extends javax.swing.JFrame {
    
    ArrayList<Cliente> clientesActuales = new ArrayList<>();
    
    Motocicleta moto1 = new Motocicleta(2020, "Diavel", "Monster", "Negra", 9000.00, "Ducati");
    Motocicleta moto2 = new Motocicleta(2020, "Road King", "Touring", "Azul", 15000.00, "Harley Davidson");
    Motocicleta moto3 = new Motocicleta(2021, "Ninja", "Sport", "Verde", 12000.00, "Kawasaki");
    Motocicleta[] motos={moto1,moto2,moto3};
    
    ImageIcon diavel = new ImageIcon(getClass().getResource("/Motocicletas/Ducati Diavel Negra 2020.png"));
    ImageIcon roadKing = new ImageIcon(getClass().getResource("/Motocicletas/Harley Davidson Road King Azul 2020.png"));
    ImageIcon ninja = new ImageIcon(getClass().getResource("/Motocicletas/Kawasaki Ninja Verde 2021.jpg"));
    
    
    /**
     * Creates new form GUIbici
     */
    public FrmMoto() {
        initComponents();
        panelinfoMoto.setVisible(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbMotocicletas = new javax.swing.JComboBox<>();
        btnMostrarInfoMoto = new javax.swing.JButton();
        btnReservarMoto = new javax.swing.JButton();
        panelinfoMoto = new javax.swing.JPanel();
        lblfotoMoto = new javax.swing.JLabel();
        btnCerrarInfoMoto = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txainfoMoto = new javax.swing.JTextArea();
        lblFondoMotocicleta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Motocicletas");
        setBackground(new java.awt.Color(0, 0, 0));
        setMaximumSize(new java.awt.Dimension(505, 602));
        setMinimumSize(new java.awt.Dimension(505, 602));
        setPreferredSize(new java.awt.Dimension(505, 602));
        setResizable(false);
        getContentPane().setLayout(null);

        cmbMotocicletas.setBackground(new java.awt.Color(0, 0, 0));
        cmbMotocicletas.setFont(new java.awt.Font("Wide Latin", 0, 12)); // NOI18N
        cmbMotocicletas.setForeground(new java.awt.Color(255, 255, 255));
        cmbMotocicletas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una motocicleta...", "Diavel", "Road King", "Ninja" }));
        getContentPane().add(cmbMotocicletas);
        cmbMotocicletas.setBounds(90, 90, 330, 40);

        btnMostrarInfoMoto.setBackground(new java.awt.Color(0, 0, 0));
        btnMostrarInfoMoto.setFont(new java.awt.Font("Wide Latin", 0, 12)); // NOI18N
        btnMostrarInfoMoto.setForeground(new java.awt.Color(255, 255, 255));
        btnMostrarInfoMoto.setText("Ver info de la moto");
        btnMostrarInfoMoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarInfoMotoActionPerformed(evt);
            }
        });
        getContentPane().add(btnMostrarInfoMoto);
        btnMostrarInfoMoto.setBounds(140, 150, 230, 30);

        btnReservarMoto.setBackground(new java.awt.Color(0, 0, 0));
        btnReservarMoto.setFont(new java.awt.Font("Wide Latin", 0, 12)); // NOI18N
        btnReservarMoto.setForeground(new java.awt.Color(255, 255, 255));
        btnReservarMoto.setText("Reservar");
        btnReservarMoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservarMotoActionPerformed(evt);
            }
        });
        getContentPane().add(btnReservarMoto);
        btnReservarMoto.setBounds(190, 200, 130, 40);

        panelinfoMoto.setBackground(new java.awt.Color(102, 102, 102));
        panelinfoMoto.setBorder(new javax.swing.border.MatteBorder(null));
        panelinfoMoto.setLayout(null);
        panelinfoMoto.add(lblfotoMoto);
        lblfotoMoto.setBounds(240, 10, 210, 230);

        btnCerrarInfoMoto.setBackground(new java.awt.Color(153, 153, 153));
        btnCerrarInfoMoto.setFont(new java.awt.Font("Wide Latin", 0, 14)); // NOI18N
        btnCerrarInfoMoto.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrarInfoMoto.setText("Cerrar");
        btnCerrarInfoMoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarInfoMotoActionPerformed(evt);
            }
        });
        panelinfoMoto.add(btnCerrarInfoMoto);
        btnCerrarInfoMoto.setBounds(170, 250, 120, 40);

        txainfoMoto.setBackground(new java.awt.Color(204, 204, 204));
        txainfoMoto.setColumns(20);
        txainfoMoto.setFont(new java.awt.Font("Wide Latin", 0, 10)); // NOI18N
        txainfoMoto.setRows(5);
        jScrollPane1.setViewportView(txainfoMoto);

        panelinfoMoto.add(jScrollPane1);
        jScrollPane1.setBounds(10, 10, 220, 230);

        getContentPane().add(panelinfoMoto);
        panelinfoMoto.setBounds(20, 250, 460, 310);

        lblFondoMotocicleta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondos/Fondo Interfaz Motocicleta.png"))); // NOI18N
        getContentPane().add(lblFondoMotocicleta);
        lblFondoMotocicleta.setBounds(0, 0, 510, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReservarMotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservarMotoActionPerformed
        // TODO add your handling code here:
        int index = cmbMotocicletas.getSelectedIndex() - 1;
        Cliente clienteActual = clientesActuales.get(clientesActuales.size()-1);
        int respuesta = JOptionPane.showConfirmDialog(rootPane, "¿Está seguro de querer reservar un " + motos[index].getModelo() + "?","Confirmación", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(respuesta == JOptionPane.YES_OPTION){
            clienteActual.setVehiculoReservado(motos[index]);
            JOptionPane.showMessageDialog(rootPane, clienteActual.toString()+
                    "\n\nGracias por darnos el honor de ayudarle a escoger su próxima motocicleta.");
            this.setVisible(false);
            VehículosKAR interfaz = new VehículosKAR();
            interfaz.clientes = clientesActuales;
            interfaz.setVisible(true);
        }
        else{
            cmbMotocicletas.setSelectedIndex(0);
            panelinfoMoto.setVisible(false);
        }        

    }//GEN-LAST:event_btnReservarMotoActionPerformed

    private void btnMostrarInfoMotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarInfoMotoActionPerformed
        // TODO add your handling code here:
        int index = cmbMotocicletas.getSelectedIndex();

        switch (index) {
            case 1:
                panelinfoMoto.setVisible(true);
                Icon imgDiavel = new ImageIcon(diavel.getImage().getScaledInstance(lblfotoMoto.getWidth(), lblfotoMoto.getHeight(), Image.SCALE_DEFAULT));
                lblfotoMoto.setIcon(imgDiavel);
                txainfoMoto.setText(moto1.presentarInfo()); 
                break;
            case 2:
                panelinfoMoto.setVisible(true);
                Icon imgroadKing = new ImageIcon(roadKing.getImage().getScaledInstance(lblfotoMoto.getWidth(), lblfotoMoto.getHeight(), Image.SCALE_DEFAULT));
                lblfotoMoto.setIcon(imgroadKing);
                txainfoMoto.setText(moto2.presentarInfo());                
                break;
            case 3:
                panelinfoMoto.setVisible(true); 
                Icon imgninja = new ImageIcon(ninja.getImage().getScaledInstance(lblfotoMoto.getWidth(), lblfotoMoto.getHeight(), Image.SCALE_DEFAULT));
                lblfotoMoto.setIcon(imgninja);
                txainfoMoto.setText(moto3.presentarInfo());
                break;
            default:
                JOptionPane.showMessageDialog(rootPane, "Seleccione una moto para ver su información");
        }
    }//GEN-LAST:event_btnMostrarInfoMotoActionPerformed

    private void btnCerrarInfoMotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarInfoMotoActionPerformed
        // TODO add your handling code here:
            panelinfoMoto.setVisible(false);
            cmbMotocicletas.setSelectedIndex(0);
    }//GEN-LAST:event_btnCerrarInfoMotoActionPerformed

//        java.awt.EventQueue.invokeLater(new Runnable() {
//            @Override
//            public void run() {
//                new VehículosKAR().setVisible(true)
//                ;
//            } 
//        });
//        FrmMoto.this.setVisible(false);
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMoto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMoto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMoto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMoto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMoto().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarInfoMoto;
    private javax.swing.JButton btnMostrarInfoMoto;
    private javax.swing.JButton btnReservarMoto;
    private javax.swing.JComboBox<String> cmbMotocicletas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFondoMotocicleta;
    private javax.swing.JLabel lblfotoMoto;
    private javax.swing.JPanel panelinfoMoto;
    private javax.swing.JTextArea txainfoMoto;
    // End of variables declaration//GEN-END:variables
}
